[project]
name = "ml-ai-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Saniya1976", email = "saniyakumari1976@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "groq>=1.7.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
]

[project.scripts]
ml-ai-learn = "ml_ai_learn:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
